#!/bin/sh

DESKTOP_FILE='[Desktop Entry]
Comment=CoDi functionalitites
Exec=/usr/lib/codi/codiServer.py
GenericName=
Icon=system-run
MimeType=
Name=
Path=
StartupNotify=true
Terminal=false
TerminalOptions=
Type=Application
X-DBUS-ServiceName=
X-DBUS-StartupType=
X-KDE-SubstituteUID=false
X-KDE-Username='

echo "Installing autostart script for existing users..."
for username in `ls /home`;
    do 
    DEST="/home/$username/.config/autostart/codi.desktop"
    echo "Installing codi.desktop in $DEST"
    echo "$DESKTOP_FILE" > $DEST
    chown $username.$username $DEST
done

exit 0
